# Generated by Django 5.1.6 on 2026-02-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cow_id', models.CharField(help_text='Unique identifier for the cow from ESP32 collar', max_length=50, unique=True)),
                ('temperature', models.FloatField(blank=True, help_text='Body temperature in Celsius', null=True)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate in BPM', null=True)),
                ('activity_level', models.IntegerField(blank=True, help_text='Activity level (steps or movement count)', null=True)),
                ('battery_level', models.FloatField(blank=True, help_text='Battery percentage (0-100)', null=True)),
                ('latitude', models.FloatField(blank=True, help_text='GPS latitude coordinate', null=True)),
                ('longitude', models.FloatField(blank=True, help_text='GPS longitude coordinate', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the data was received')),
                ('raw_data', models.JSONField(blank=True, help_text='Original JSON data received from ESP32', null=True)),
            ],
        ),
    ]
