# Generated by Django 5.1.6 on 2026-02-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cow',
            name='cow_id',
            field=models.CharField(help_text='Identifier for the cow from ESP32 collar', max_length=50),
        ),
    ]
