# Generated by Django 5.1.6 on 2026-04-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cow_cow_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cow',
            name='accel_x',
            field=models.FloatField(blank=True, help_text='Accelerometer X axis', null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='accel_y',
            field=models.FloatField(blank=True, help_text='Accelerometer Y axis', null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='accel_z',
            field=models.FloatField(blank=True, help_text='Accelerometer Z axis', null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='activity_status',
            field=models.CharField(blank=True, help_text='Activity status (Moving/Idle)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='gyro_x',
            field=models.FloatField(blank=True, help_text='Gyroscope X axis', null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='gyro_y',
            field=models.FloatField(blank=True, help_text='Gyroscope Y axis', null=True),
        ),
        migrations.AddField(
            model_name='cow',
            name='gyro_z',
            field=models.FloatField(blank=True, help_text='Gyroscope Z axis', null=True),
        ),
    ]
